server:
  port: 8080

spring:
  application:
    name: inventory-management
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_inventory?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    com.warehouse.inventory: DEBUG

app:
  cors:
    allowed-origin: http://localhost:5173
  jwt:
    secret: "warehouse-inventory-jwt-secret-key-for-development-only-min32chars"
    expiration: 86400000
